# Example NixOS Host Configuration
# See: .agents/skills/nixos-best-practices/rules/host-organization.md

{ inputs, config, pkgs, pkgs-stable, system, ... }:

{
  imports = [
    # Import hardware configuration (generated by nixos-generate-config)
    # IMPORTANT: Don't edit hardware-configuration.nix manually!
    # See: .agents/skills/nixos-best-practices/rules/common-mistakes.md
    ./hardware-configuration.nix
    
    # Import shared NixOS base configuration
    ../nixos-base.nix
    
    # Import Home Manager NixOS module
    inputs.home-manager.nixosModules.home-manager
    
    # Import Agenix for secrets management
    inputs.agenix.nixosModules.default
    
    # Home Manager configuration inline
    # CRITICAL: This is where you configure Home Manager with useGlobalPkgs = true
    # See: .agents/skills/nixos-best-practices/rules/overlay-scope.md
    {
      home-manager = {
        # CRITICAL: useGlobalPkgs = true means overlays MUST be defined HERE,
        # not in home.nix! See overlay-scope.md for details.
        useGlobalPkgs = true;
        useUserPackages = true;
        
        # Import Home Manager configuration for this user
        # TODO: Replace 'username' with your actual username
        users.username = import ./home.nix;
        
        # Pass extra arguments to Home Manager
        extraSpecialArgs = {
          inherit inputs pkgs-stable system;
        };
      };
      
      # ========================================================================
      # Overlays Configuration
      # ========================================================================
      # CRITICAL: With useGlobalPkgs = true, overlays MUST be defined HERE!
      # Overlays defined in home.nix will be IGNORED.
      # See: .agents/skills/nixos-best-practices/rules/overlay-scope.md
      
      nixpkgs.overlays = [
        # Add your overlays here
        # Example: inputs.some-flake.overlays.default
        # Example: (import ../overlays/example-overlay.nix)
      ];
    }
  ];

  # ============================================================================
  # Host-Specific Configuration
  # ============================================================================
  
  # Set hostname
  # TODO: Replace with your actual hostname
  networking.hostName = "example-nixos";

  # ============================================================================
  # Boot Configuration (Host-Specific)
  # ============================================================================
  
  # Use systemd-boot (UEFI)
  boot.loader = {
    systemd-boot.enable = true;
    efi.canTouchEfiVariables = true;
  };
  
  # Or use GRUB (uncomment if needed instead of systemd-boot)
  # boot.loader.grub = {
  #   enable = true;
  #   device = "/dev/sda";  # or "nodev" for UEFI
  #   useOSProber = true;    # Detect other operating systems
  # };

  # ============================================================================
  # Hardware Configuration (Host-Specific)
  # ============================================================================
  
  # Enable sound with PipeWire
  services.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # Enable graphics (if using X11 or Wayland)
  hardware.graphics = {
    enable = true;
    enable32Bit = true;  # For 32-bit apps/games
  };

  # ============================================================================
  # Desktop Environment / Window Manager
  # ============================================================================
  # Uncomment one of these sections based on your preference
  
  # GNOME
  # services.xserver = {
  #   enable = true;
  #   displayManager.gdm.enable = true;
  #   desktopManager.gnome.enable = true;
  # };
  
  # KDE Plasma
  # services.xserver = {
  #   enable = true;
  #   displayManager.sddm.enable = true;
  #   desktopManager.plasma5.enable = true;
  # };
  
  # i3 Window Manager
  # services.xserver = {
  #   enable = true;
  #   windowManager.i3.enable = true;
  #   displayManager.lightdm.enable = true;
  # };

  # ============================================================================
  # Additional Services (Host-Specific)
  # ============================================================================
  
  # Enable Docker (optional)
  # virtualisation.docker = {
  #   enable = true;
  #   enableOnBoot = true;
  # };
  
  # Enable libvirtd for virtual machines (optional)
  # virtualisation.libvirtd.enable = true;

  # ============================================================================
  # Custom Modules
  # ============================================================================
  # Import custom modules as needed
  # Example: imports = [ ../../modules/nixos/example-module.nix ];

  # ============================================================================
  # State Version
  # ============================================================================
  # This value determines the NixOS release with which your system is compatible
  # Don't change this unless you know what you're doing!
  system.stateVersion = "24.05";
}
